version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app 
    command: bash -c "yarn install && yarn dev"
    ports:
      - "3000:3000"