version: '3'
services:
  app:
    container_name: myapp-container-fe
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: bash -c "yarn install && yarn dev-https"
    ports:
      - "3000:3000"
