version: '3'
services:
  app:
    container_name: $APP_NAME-container-fe
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: bash -c "yarn install && yarn dev"
    ports:
      - "3000:3000"
networks:
  default:
    name: app-external
    external: true