version: '3'
services:
  app:
    container_name: a1-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app 
    command: bash -c "yarn install && yarn dev"
    ports:
      - "3000:3000"
networks:
  default:
    name: myapp-network
    external: true